[package]
name = "orbimage"
description = "Orbital image features"
repository = "https://github.com/redox-os/orbimage"
version = "0.1.14"
license-file = "LICENSE"
readme = "README.md"
authors = ["Jeremy Soller <jackpot51@gmail.com>"]

[dependencies]
orbclient = "0.3"
image = "0.12"
resize = "0.2"
